- Target: nmaguiar/secutils:build (alpine 3.23.0_alpha20250612)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-12798
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:4f2d5cc653c19ec482b7ffe2ecf0f6a0fb585a0dc995d025a4c5f06b607e5e56
      DiffID: sha256:a47f959830dc7f9089ab12b7962af67f3f0f8caa8d1687091e5ae09e692bba2a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12798
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: arbitrary code execution via JaninoEventEvaluator'
    Description: "ACE vulnerability in JaninoEventEvaluator  by QOS.CH logback-core\n      upto including version 0.1 to 1.3.14 and\_1.4.0 to 1.5.12 in Java applications allows\n      attacker to execute arbitrary code by compromising an existing\n      logback configuration file or by injecting an environment variable\n      before program execution.\n\n\n\n\n\nMalicious logback configuration files can allow the attacker to execute \narbitrary code using the JaninoEventEvaluator extension.\n\n\n\nA successful attack requires the user to have write access to a \nconfiguration file. Alternatively, the attacker could inject a malicious \nenvironment variable pointing to a malicious configuration file. In both \ncases, the attack requires existing privilege."
    Severity: MEDIUM
    CweIDs:
    - CWE-917
    VendorSeverity:
      ghsa: 2
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:H/A:L
        V3Score: 5.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12798
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/2cb6d520df7592ef1c3a198f1b5df3c10c93e183
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12798
    - https://www.cve.org/CVERecord?id=CVE-2024-12798
    PublishedDate: '2024-12-19T16:15:07.557Z'
    LastModifiedDate: '2025-01-03T14:15:24.37Z'
  - VulnerabilityID: CVE-2024-12801
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:4f2d5cc653c19ec482b7ffe2ecf0f6a0fb585a0dc995d025a4c5f06b607e5e56
      DiffID: sha256:a47f959830dc7f9089ab12b7962af67f3f0f8caa8d1687091e5ae09e692bba2a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12801
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: SaxEventRecorder vulnerable to Server-Side Request Forgery (SSRF) attacks'
    Description: "Server-Side Request Forgery (SSRF) in SaxEventRecorder by QOS.CH logback version 0.1 to 1.3.14 and 1.4.0 to 1.5.12\_ on the Java platform, allows an attacker to \nforge requests by compromising logback configuration files in XML.\n\n\n\nThe attacks involves the modification of DOCTYPE declaration in\_ XML configuration files."
    Severity: LOW
    CweIDs:
    - CWE-918
    VendorSeverity:
      ghsa: 1
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:N
        V3Score: 3.3
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12801
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/5f05041cba4c4ac0a62748c5c527a2da48999f2d
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12801
    - https://www.cve.org/CVERecord?id=CVE-2024-12801
    PublishedDate: '2024-12-19T17:15:08.93Z'
    LastModifiedDate: '2025-01-03T14:15:24.5Z'
  - VulnerabilityID: CVE-2025-48734
    PkgName: commons-beanutils:commons-beanutils
    PkgPath: opt/dependency-check/lib/commons-beanutils-1.9.4.jar
    PkgIdentifier:
      PURL: pkg:maven/commons-beanutils/commons-beanutils@1.9.4
      UID: 87543632af4cfff7
    InstalledVersion: 1.9.4
    FixedVersion: 1.11.0
    Status: fixed
    Layer:
      Digest: sha256:4f2d5cc653c19ec482b7ffe2ecf0f6a0fb585a0dc995d025a4c5f06b607e5e56
      DiffID: sha256:a47f959830dc7f9089ab12b7962af67f3f0f8caa8d1687091e5ae09e692bba2a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-48734
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'commons-beanutils: Apache Commons BeanUtils: PropertyUtilsBean does not suppresses an enum''s declaredClass property by default'
    Description: |-
      Improper Access Control vulnerability in Apache Commons.



      A special BeanIntrospector class was added in version 1.9.2. This can be used to stop attackers from using the declared class property of Java enum objects to get access to the classloader. However this protection was not enabled by default. PropertyUtilsBean (and consequently BeanUtilsBean) now disallows declared class level property access by default.





      Releases 1.11.0 and 2.0.0-M2 address a potential security issue when accessing enum properties in an uncontrolled way. If an application using Commons BeanUtils passes property paths from an external source directly to the getProperty() method of PropertyUtilsBean, an attacker can access the enum’s class loader via the “declaredClass” property available on all Java “enum” objects. Accessing the enum’s “declaredClass” allows remote attackers to access the ClassLoader and execute arbitrary code. The same issue exists with PropertyUtilsBean.getNestedProperty().
      Starting in versions 1.11.0 and 2.0.0-M2 a special BeanIntrospector suppresses the “declaredClass” property. Note that this new BeanIntrospector is enabled by default, but you can disable it to regain the old behavior; see section 2.5 of the user's guide and the unit tests.

      This issue affects Apache Commons BeanUtils 1.x before 1.11.0, and 2.x before 2.0.0-M2.Users of the artifact commons-beanutils:commons-beanutils

       1.x are recommended to upgrade to version 1.11.0, which fixes the issue.


      Users of the artifact org.apache.commons:commons-beanutils2

       2.x are recommended to upgrade to version 2.0.0-M2, which fixes the issue.
    Severity: HIGH
    CweIDs:
    - CWE-284
    VendorSeverity:
      alma: 3
      amazon: 3
      ghsa: 3
      oracle-oval: 3
      redhat: 3
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
        V3Score: 8.8
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
        V3Score: 8.8
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/28/6
    - https://access.redhat.com/errata/RHSA-2025:9114
    - https://access.redhat.com/security/cve/CVE-2025-48734
    - https://bugzilla.redhat.com/2368956
    - https://errata.almalinux.org/9/ALSA-2025-9114.html
    - https://github.com/advisories/GHSA-wxr5-93ph-8wr9
    - https://github.com/apache/commons-beanutils
    - https://github.com/apache/commons-beanutils/commit/28ad955a1613ed5885870cc7da52093c1ce739dc
    - https://github.com/apache/commons-beanutils/commit/bd20740da25b69552ddef8523beec0837297eaf9
    - https://linux.oracle.com/cve/CVE-2025-48734.html
    - https://linux.oracle.com/errata/ELSA-2025-9318.html
    - https://lists.apache.org/thread/s0hb3jkfj5f3ryx6c57zqtfohb0of1g9
    - https://nvd.nist.gov/vuln/detail/CVE-2025-48734
    - https://www.cve.org/CVERecord?id=CVE-2025-48734
    - https://www.openwall.com/lists/oss-security/2025/05/28/6
    PublishedDate: '2025-05-28T14:15:34.07Z'
    LastModifiedDate: '2025-06-09T18:56:26.37Z'
  - VulnerabilityID: CVE-2025-48924
    PkgName: org.apache.commons:commons-lang3
    PkgPath: openaf/openaf.jar
    PkgIdentifier:
      PURL: pkg:maven/org.apache.commons/commons-lang3@3.17.0
      UID: 36abc6aa3ef9156f
    InstalledVersion: 3.17.0
    FixedVersion: 3.18.0
    Status: fixed
    Layer:
      Digest: sha256:4f2d5cc653c19ec482b7ffe2ecf0f6a0fb585a0dc995d025a4c5f06b607e5e56
      DiffID: sha256:a47f959830dc7f9089ab12b7962af67f3f0f8caa8d1687091e5ae09e692bba2a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-48924
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'commons-lang/commons-lang: org.apache.commons/commons-lang3: Uncontrolled Recursion vulnerability in Apache Commons Lang'
    Description: "Uncontrolled Recursion vulnerability in Apache Commons Lang.\n\nThis issue affects Apache Commons Lang: Starting with\_commons-lang:commons-lang\_2.0 to 2.6, and, from org.apache.commons:commons-lang3 3.0 before\_3.18.0.\n\nThe methods ClassUtils.getClass(...) can throw\_StackOverflowError on very long inputs. Because an Error is usually not handled by applications and libraries, a \nStackOverflowError could\_cause an application to stop.\n\nUsers are recommended to upgrade to version 3.18.0, which fixes the issue."
    Severity: MEDIUM
    CweIDs:
    - CWE-674
    VendorSeverity:
      ghsa: 2
      redhat: 1
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 6.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 3.7
    References:
    - https://access.redhat.com/security/cve/CVE-2025-48924
    - https://github.com/apache/commons-lang
    - https://github.com/apache/commons-lang/commit/b424803abdb2bec818e4fbcb251ce031c22aca53
    - https://lists.apache.org/thread/bgv0lpswokgol11tloxnjfzdl7yrc1g1
    - https://nvd.nist.gov/vuln/detail/CVE-2025-48924
    - https://www.cve.org/CVERecord?id=CVE-2025-48924
    PublishedDate: '2025-07-11T15:15:24.347Z'
    LastModifiedDate: '2025-07-15T13:14:49.98Z'
  - VulnerabilityID: CVE-2025-48924
    PkgName: org.apache.commons:commons-lang3
    PkgPath: opt/dependency-check/lib/commons-lang3-3.17.0.jar
    PkgIdentifier:
      PURL: pkg:maven/org.apache.commons/commons-lang3@3.17.0
      UID: 185217fb76d896ee
    InstalledVersion: 3.17.0
    FixedVersion: 3.18.0
    Status: fixed
    Layer:
      Digest: sha256:4f2d5cc653c19ec482b7ffe2ecf0f6a0fb585a0dc995d025a4c5f06b607e5e56
      DiffID: sha256:a47f959830dc7f9089ab12b7962af67f3f0f8caa8d1687091e5ae09e692bba2a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-48924
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'commons-lang/commons-lang: org.apache.commons/commons-lang3: Uncontrolled Recursion vulnerability in Apache Commons Lang'
    Description: "Uncontrolled Recursion vulnerability in Apache Commons Lang.\n\nThis issue affects Apache Commons Lang: Starting with\_commons-lang:commons-lang\_2.0 to 2.6, and, from org.apache.commons:commons-lang3 3.0 before\_3.18.0.\n\nThe methods ClassUtils.getClass(...) can throw\_StackOverflowError on very long inputs. Because an Error is usually not handled by applications and libraries, a \nStackOverflowError could\_cause an application to stop.\n\nUsers are recommended to upgrade to version 3.18.0, which fixes the issue."
    Severity: MEDIUM
    CweIDs:
    - CWE-674
    VendorSeverity:
      ghsa: 2
      redhat: 1
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 6.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 3.7
    References:
    - https://access.redhat.com/security/cve/CVE-2025-48924
    - https://github.com/apache/commons-lang
    - https://github.com/apache/commons-lang/commit/b424803abdb2bec818e4fbcb251ce031c22aca53
    - https://lists.apache.org/thread/bgv0lpswokgol11tloxnjfzdl7yrc1g1
    - https://nvd.nist.gov/vuln/detail/CVE-2025-48924
    - https://www.cve.org/CVERecord?id=CVE-2025-48924
    PublishedDate: '2025-07-11T15:15:24.347Z'
    LastModifiedDate: '2025-07-15T13:14:49.98Z'
  - VulnerabilityID: CVE-2025-27820
    PkgName: org.apache.httpcomponents.client5:httpclient5
    PkgPath: opt/dependency-check/lib/httpclient5-5.4.2.jar
    PkgIdentifier:
      PURL: pkg:maven/org.apache.httpcomponents.client5/httpclient5@5.4.2
      UID: 6ea72d58fcde5316
    InstalledVersion: 5.4.2
    FixedVersion: 5.4.3
    Status: fixed
    Layer:
      Digest: sha256:4f2d5cc653c19ec482b7ffe2ecf0f6a0fb585a0dc995d025a4c5f06b607e5e56
      DiffID: sha256:a47f959830dc7f9089ab12b7962af67f3f0f8caa8d1687091e5ae09e692bba2a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-27820
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'org.apache.httpcomponents.client5/httpclient5: Apache HttpComponents: PSL (Public Suffix List) validation bypass'
    Description: A bug in PSL validation logic in Apache HttpClient 5.4.x disables domain checks, affecting cookie management and host name verification. Discovered by the Apache HttpClient team. Fixed in the 5.4.3 release
    Severity: HIGH
    CweIDs:
    - CWE-295
    VendorSeverity:
      ghsa: 3
      redhat: 2
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:H/A:N
        V3Score: 6.5
    References:
    - https://access.redhat.com/security/cve/CVE-2025-27820
    - https://github.com/advisories/GHSA-73m2-qfq3-56cx
    - https://github.com/apache/httpcomponents-client
    - https://github.com/apache/httpcomponents-client/pull/574
    - https://github.com/apache/httpcomponents-client/pull/621
    - https://hc.apache.org/httpcomponents-client-5.4.x/index.html
    - https://lists.apache.org/thread/55xhs40ncqv97qvoocok44995xp5kqn8
    - https://nvd.nist.gov/vuln/detail/CVE-2025-27820
    - https://security.netapp.com/advisory/ntap-20250516-0003
    - https://security.netapp.com/advisory/ntap-20250516-0003/
    - https://www.cve.org/CVERecord?id=CVE-2025-27820
    PublishedDate: '2025-04-24T12:15:16.723Z'
    LastModifiedDate: '2025-07-16T14:48:52.213Z'
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
- Target: usr/bin/grype
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/syft
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/trivy
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-53547
    PkgID: helm.sh/helm/v3@v3.18.3
    PkgName: helm.sh/helm/v3
    PkgIdentifier:
      PURL: pkg:golang/helm.sh/helm/v3@v3.18.3
      UID: cf2480296004620c
    InstalledVersion: v3.18.3
    FixedVersion: 3.18.4, 3.17.4
    Status: fixed
    Layer:
      Digest: sha256:4f2d5cc653c19ec482b7ffe2ecf0f6a0fb585a0dc995d025a4c5f06b607e5e56
      DiffID: sha256:a47f959830dc7f9089ab12b7962af67f3f0f8caa8d1687091e5ae09e692bba2a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-53547
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'helm.sh/helm/v3: Helm Chart Code Execution'
    Description: Helm is a package manager for Charts for Kubernetes. Prior to 3.18.4, a specially crafted Chart.yaml file along with a specially linked Chart.lock file can lead to local code execution when dependencies are updated. Fields in a Chart.yaml file, that are carried over to a Chart.lock file when dependencies are updated and this file is written, can be crafted in a way that can cause execution if that same content were in a file that is executed (e.g., a bash.rc file or shell script). If the Chart.lock file is symlinked to one of these files updating dependencies will write the lock file content to the symlinked file. This can lead to unwanted execution. Helm warns of the symlinked file but did not stop execution due to symlinking. This issue has been resolved in Helm v3.18.4.
    Severity: HIGH
    CweIDs:
    - CWE-94
    VendorSeverity:
      bitnami: 3
      ghsa: 3
      redhat: 3
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:C/C:L/I:H/A:H
        V3Score: 8.5
      ghsa:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:C/C:L/I:H/A:H
        V3Score: 8.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:C/C:L/I:H/A:H
        V3Score: 8.5
    References:
    - https://access.redhat.com/security/cve/CVE-2025-53547
    - https://github.com/helm/helm
    - https://github.com/helm/helm/commit/4b8e61093d8f579f1165cdc6bd4b43fa5455f571
    - https://github.com/helm/helm/security/advisories/GHSA-557j-xg8c-q2mm
    - https://news.ycombinator.com/item?id=44506696
    - https://nvd.nist.gov/vuln/detail/CVE-2025-53547
    - https://www.cve.org/CVERecord?id=CVE-2025-53547
    PublishedDate: '2025-07-08T22:15:27.897Z'
    LastModifiedDate: '2025-07-10T13:18:53.83Z'
- Target: usr/bin/trivy_cve_query
  Class: lang-pkgs
  Type: gobinary
