- Target: nmaguiar/secutils:build (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-31498
    PkgID: c-ares@1.34.4-r0
    PkgName: c-ares
    PkgIdentifier:
      PURL: pkg:apk/alpine/c-ares@1.34.4-r0?arch=x86_64&distro=3.22.0_alpha20250108
      UID: d08c3f13cf9b48a0
    InstalledVersion: 1.34.4-r0
    FixedVersion: 1.34.5-r0
    Status: fixed
    Layer:
      Digest: sha256:87f78453ae9872ab60c96f6d78e7f81a532110b9a2510e5ec5a18c10bed70770
      DiffID: sha256:d44b728dcf951f4c7f33bd3315e4e3efc556f40d9cca3b5879368c97c03de92c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-31498
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: c-ares is an asynchronous resolver library. From 1.32.3 through 1.34.4 ...
    Description: c-ares is an asynchronous resolver library. From 1.32.3 through 1.34.4, there is a use-after-free in read_answers() when process_answer() may re-enqueue a query either due to a DNS Cookie Failure or when the upstream server does not properly support EDNS, or possibly on TCP queries if the remote closed the connection immediately after a response. If there was an issue trying to put that new transaction on the wire, it would close the connection handle, but read_answers() was still expecting the connection handle to be available to possibly dequeue other responses. In theory a remote attacker might be able to trigger this by flooding the target with ICMP UNREACHABLE packets if they also control the upstream nameserver and can return a result with one of those conditions, this has been untested. Otherwise only a local attacker might be able to change system behavior to make send()/write() return a failure condition. This vulnerability is fixed in 1.34.5.
    Severity: UNKNOWN
    CweIDs:
    - CWE-416
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/08/3
    - https://github.com/c-ares/c-ares/commit/29d38719112639d8c0ba910254a3dd4f482ea2d1
    - https://github.com/c-ares/c-ares/pull/821
    - https://github.com/c-ares/c-ares/security/advisories/GHSA-6hxc-62jh-p29v
    PublishedDate: '2025-04-08T14:15:35.293Z'
    LastModifiedDate: '2025-04-08T15:15:50.31Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-12798
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:87f78453ae9872ab60c96f6d78e7f81a532110b9a2510e5ec5a18c10bed70770
      DiffID: sha256:d44b728dcf951f4c7f33bd3315e4e3efc556f40d9cca3b5879368c97c03de92c
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12798
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: arbitrary code execution via JaninoEventEvaluator'
    Description: "ACE vulnerability in JaninoEventEvaluator  by QOS.CH logback-core\n      upto including version 0.1 to 1.3.14 and\_1.4.0 to 1.5.12 in Java applications allows\n      attacker to execute arbitrary code by compromising an existing\n      logback configuration file or by injecting an environment variable\n      before program execution.\n\n\n\n\n\nMalicious logback configuration files can allow the attacker to execute \narbitrary code using the JaninoEventEvaluator extension.\n\n\n\nA successful attack requires the user to have write access to a \nconfiguration file. Alternatively, the attacker could inject a malicious \nenvironment variable pointing to a malicious configuration file. In both \ncases, the attack requires existing privilege."
    Severity: MEDIUM
    CweIDs:
    - CWE-917
    VendorSeverity:
      ghsa: 2
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:H/A:L
        V3Score: 5.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12798
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/2cb6d520df7592ef1c3a198f1b5df3c10c93e183
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12798
    - https://www.cve.org/CVERecord?id=CVE-2024-12798
    PublishedDate: '2024-12-19T16:15:07.557Z'
    LastModifiedDate: '2025-01-03T14:15:24.37Z'
  - VulnerabilityID: CVE-2024-12801
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:87f78453ae9872ab60c96f6d78e7f81a532110b9a2510e5ec5a18c10bed70770
      DiffID: sha256:d44b728dcf951f4c7f33bd3315e4e3efc556f40d9cca3b5879368c97c03de92c
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12801
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: SaxEventRecorder vulnerable to Server-Side Request Forgery (SSRF) attacks'
    Description: "Server-Side Request Forgery (SSRF) in SaxEventRecorder by QOS.CH logback version 0.1 to 1.3.14 and 1.4.0 to 1.5.12\_ on the Java platform, allows an attacker to \nforge requests by compromising logback configuration files in XML.\n\n\n\nThe attacks involves the modification of DOCTYPE declaration in\_ XML configuration files."
    Severity: LOW
    CweIDs:
    - CWE-918
    VendorSeverity:
      ghsa: 1
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:N
        V3Score: 3.3
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12801
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/5f05041cba4c4ac0a62748c5c527a2da48999f2d
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12801
    - https://www.cve.org/CVERecord?id=CVE-2024-12801
    PublishedDate: '2024-12-19T17:15:08.93Z'
    LastModifiedDate: '2025-01-03T14:15:24.5Z'
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
- Target: usr/bin/grype
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-22871
    PkgID: stdlib@v1.24.1
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.24.1
      UID: 65ca895f24942279
    InstalledVersion: v1.24.1
    FixedVersion: 1.23.8, 1.24.2
    Status: fixed
    Layer:
      Digest: sha256:87f78453ae9872ab60c96f6d78e7f81a532110b9a2510e5ec5a18c10bed70770
      DiffID: sha256:d44b728dcf951f4c7f33bd3315e4e3efc556f40d9cca3b5879368c97c03de92c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22871
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: The net/http package improperly accepts a bare LF as a line terminator ...
    Description: The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.
    Severity: UNKNOWN
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/04/4
    - https://go.dev/cl/652998
    - https://go.dev/issue/71988
    - https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk
    - https://pkg.go.dev/vuln/GO-2025-3563
    PublishedDate: '2025-04-08T20:15:20.183Z'
    LastModifiedDate: '2025-04-08T21:15:48.173Z'
- Target: usr/bin/syft
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-22871
    PkgID: stdlib@v1.24.1
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.24.1
      UID: c16316e32d1afd39
    InstalledVersion: v1.24.1
    FixedVersion: 1.23.8, 1.24.2
    Status: fixed
    Layer:
      Digest: sha256:87f78453ae9872ab60c96f6d78e7f81a532110b9a2510e5ec5a18c10bed70770
      DiffID: sha256:d44b728dcf951f4c7f33bd3315e4e3efc556f40d9cca3b5879368c97c03de92c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22871
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: The net/http package improperly accepts a bare LF as a line terminator ...
    Description: The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.
    Severity: UNKNOWN
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/04/4
    - https://go.dev/cl/652998
    - https://go.dev/issue/71988
    - https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk
    - https://pkg.go.dev/vuln/GO-2025-3563
    PublishedDate: '2025-04-08T20:15:20.183Z'
    LastModifiedDate: '2025-04-08T21:15:48.173Z'
- Target: usr/bin/trivy
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-22871
    PkgID: stdlib@v1.24.1
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.24.1
      UID: 7aba090ce18913b7
    InstalledVersion: v1.24.1
    FixedVersion: 1.23.8, 1.24.2
    Status: fixed
    Layer:
      Digest: sha256:87f78453ae9872ab60c96f6d78e7f81a532110b9a2510e5ec5a18c10bed70770
      DiffID: sha256:d44b728dcf951f4c7f33bd3315e4e3efc556f40d9cca3b5879368c97c03de92c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22871
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: The net/http package improperly accepts a bare LF as a line terminator ...
    Description: The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.
    Severity: UNKNOWN
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/04/4
    - https://go.dev/cl/652998
    - https://go.dev/issue/71988
    - https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk
    - https://pkg.go.dev/vuln/GO-2025-3563
    PublishedDate: '2025-04-08T20:15:20.183Z'
    LastModifiedDate: '2025-04-08T21:15:48.173Z'
- Target: usr/bin/trivy_cve_query
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-22871
    PkgID: stdlib@v1.24.1
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.24.1
      UID: b5fb81b8f7a10cb5
    InstalledVersion: v1.24.1
    FixedVersion: 1.23.8, 1.24.2
    Status: fixed
    Layer:
      Digest: sha256:87f78453ae9872ab60c96f6d78e7f81a532110b9a2510e5ec5a18c10bed70770
      DiffID: sha256:d44b728dcf951f4c7f33bd3315e4e3efc556f40d9cca3b5879368c97c03de92c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22871
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: The net/http package improperly accepts a bare LF as a line terminator ...
    Description: The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.
    Severity: UNKNOWN
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/04/4
    - https://go.dev/cl/652998
    - https://go.dev/issue/71988
    - https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk
    - https://pkg.go.dev/vuln/GO-2025-3563
    PublishedDate: '2025-04-08T20:15:20.183Z'
    LastModifiedDate: '2025-04-08T21:15:48.173Z'
