- Target: nmaguiar/secutils:build (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-12798
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:27cf058be0e6ee775f4124c73b6d2a9c74f310531abd51cd3213434917fc0aca
      DiffID: sha256:422fe88498129205837a57b380c2d1dc362fe7793e3a99ed0d9fb43d20cd5840
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12798
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: arbitrary code execution via JaninoEventEvaluator'
    Description: "ACE vulnerability in JaninoEventEvaluator  by QOS.CH logback-core\n      upto including version 0.1 to 1.3.14 and\_1.4.0 to 1.5.12 in Java applications allows\n      attacker to execute arbitrary code by compromising an existing\n      logback configuration file or by injecting an environment variable\n      before program execution.\n\n\n\n\n\nMalicious logback configuration files can allow the attacker to execute \narbitrary code using the JaninoEventEvaluator extension.\n\n\n\nA successful attack requires the user to have write access to a \nconfiguration file. Alternatively, the attacker could inject a malicious \nenvironment variable pointing to a malicious configuration file. In both \ncases, the attack requires existing privilege."
    Severity: MEDIUM
    CweIDs:
    - CWE-917
    VendorSeverity:
      ghsa: 2
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:H/A:L
        V3Score: 5.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12798
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/2cb6d520df7592ef1c3a198f1b5df3c10c93e183
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12798
    - https://www.cve.org/CVERecord?id=CVE-2024-12798
    PublishedDate: '2024-12-19T16:15:07.557Z'
    LastModifiedDate: '2025-01-03T14:15:24.37Z'
  - VulnerabilityID: CVE-2024-12801
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:27cf058be0e6ee775f4124c73b6d2a9c74f310531abd51cd3213434917fc0aca
      DiffID: sha256:422fe88498129205837a57b380c2d1dc362fe7793e3a99ed0d9fb43d20cd5840
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12801
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: SaxEventRecorder vulnerable to Server-Side Request Forgery (SSRF) attacks'
    Description: "Server-Side Request Forgery (SSRF) in SaxEventRecorder by QOS.CH logback version 0.1 to 1.3.14 and 1.4.0 to 1.5.12\_ on the Java platform, allows an attacker to \nforge requests by compromising logback configuration files in XML.\n\n\n\nThe attacks involves the modification of DOCTYPE declaration in\_ XML configuration files."
    Severity: LOW
    CweIDs:
    - CWE-918
    VendorSeverity:
      ghsa: 1
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:N
        V3Score: 3.3
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12801
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/5f05041cba4c4ac0a62748c5c527a2da48999f2d
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12801
    - https://www.cve.org/CVERecord?id=CVE-2024-12801
    PublishedDate: '2024-12-19T17:15:08.93Z'
    LastModifiedDate: '2025-01-03T14:15:24.5Z'
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
- Target: usr/bin/grype
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-45336
    PkgID: stdlib@v1.23.4
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.23.4
      UID: 68fb6f4b35d69483
    InstalledVersion: v1.23.4
    FixedVersion: 1.22.11, 1.23.5, 1.24.0-rc.2
    Status: fixed
    Layer:
      Digest: sha256:27cf058be0e6ee775f4124c73b6d2a9c74f310531abd51cd3213434917fc0aca
      DiffID: sha256:422fe88498129205837a57b380c2d1dc362fe7793e3a99ed0d9fb43d20cd5840
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45336
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'golang: net/http: net/http: sensitive headers incorrectly sent after cross-domain redirect'
    Description: The HTTP client drops sensitive headers after following a cross-domain redirect. For example, a request to a.com/ containing an Authorization header which is redirected to b.com/ will not send that header to b.com. In the event that the client received a subsequent same-domain redirect, however, the sensitive headers would be restored. For example, a chain of redirects from a.com/, to b.com/1, and finally to b.com/2 would incorrectly send the Authorization header to b.com/2.
    Severity: MEDIUM
    VendorSeverity:
      bitnami: 2
      redhat: 2
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
        V3Score: 6.1
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N
        V3Score: 5.9
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45336
    - https://go.dev/cl/643100
    - https://go.dev/issue/70530
    - https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ
    - https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45336
    - https://pkg.go.dev/vuln/GO-2025-3420
    - https://www.cve.org/CVERecord?id=CVE-2024-45336
    PublishedDate: '2025-01-28T02:15:28.807Z'
    LastModifiedDate: '2025-01-28T16:15:38.22Z'
  - VulnerabilityID: CVE-2024-45341
    PkgID: stdlib@v1.23.4
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.23.4
      UID: 68fb6f4b35d69483
    InstalledVersion: v1.23.4
    FixedVersion: 1.22.11, 1.23.5, 1.24.0-rc.2
    Status: fixed
    Layer:
      Digest: sha256:27cf058be0e6ee775f4124c73b6d2a9c74f310531abd51cd3213434917fc0aca
      DiffID: sha256:422fe88498129205837a57b380c2d1dc362fe7793e3a99ed0d9fb43d20cd5840
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45341
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'golang: crypto/x509: crypto/x509: usage of IPv6 zone IDs can bypass URI name constraints'
    Description: A certificate with a URI which has a IPv6 address with a zone ID may incorrectly satisfy a URI name constraint that applies to the certificate chain. Certificates containing URIs are not permitted in the web PKI, so this only affects users of private PKIs which make use of URIs.
    Severity: MEDIUM
    VendorSeverity:
      bitnami: 2
      redhat: 1
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
        V3Score: 6.1
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.2
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45341
    - https://go.dev/cl/643099
    - https://go.dev/issue/71156
    - https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ
    - https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45341
    - https://pkg.go.dev/vuln/GO-2025-3373
    - https://www.cve.org/CVERecord?id=CVE-2024-45341
    PublishedDate: '2025-01-28T02:15:29.147Z'
    LastModifiedDate: '2025-01-28T16:15:38.65Z'
- Target: usr/bin/syft
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-45336
    PkgID: stdlib@v1.23.4
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.23.4
      UID: 41c223d59c4dbf4f
    InstalledVersion: v1.23.4
    FixedVersion: 1.22.11, 1.23.5, 1.24.0-rc.2
    Status: fixed
    Layer:
      Digest: sha256:27cf058be0e6ee775f4124c73b6d2a9c74f310531abd51cd3213434917fc0aca
      DiffID: sha256:422fe88498129205837a57b380c2d1dc362fe7793e3a99ed0d9fb43d20cd5840
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45336
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'golang: net/http: net/http: sensitive headers incorrectly sent after cross-domain redirect'
    Description: The HTTP client drops sensitive headers after following a cross-domain redirect. For example, a request to a.com/ containing an Authorization header which is redirected to b.com/ will not send that header to b.com. In the event that the client received a subsequent same-domain redirect, however, the sensitive headers would be restored. For example, a chain of redirects from a.com/, to b.com/1, and finally to b.com/2 would incorrectly send the Authorization header to b.com/2.
    Severity: MEDIUM
    VendorSeverity:
      bitnami: 2
      redhat: 2
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
        V3Score: 6.1
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N
        V3Score: 5.9
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45336
    - https://go.dev/cl/643100
    - https://go.dev/issue/70530
    - https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ
    - https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45336
    - https://pkg.go.dev/vuln/GO-2025-3420
    - https://www.cve.org/CVERecord?id=CVE-2024-45336
    PublishedDate: '2025-01-28T02:15:28.807Z'
    LastModifiedDate: '2025-01-28T16:15:38.22Z'
  - VulnerabilityID: CVE-2024-45341
    PkgID: stdlib@v1.23.4
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.23.4
      UID: 41c223d59c4dbf4f
    InstalledVersion: v1.23.4
    FixedVersion: 1.22.11, 1.23.5, 1.24.0-rc.2
    Status: fixed
    Layer:
      Digest: sha256:27cf058be0e6ee775f4124c73b6d2a9c74f310531abd51cd3213434917fc0aca
      DiffID: sha256:422fe88498129205837a57b380c2d1dc362fe7793e3a99ed0d9fb43d20cd5840
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45341
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'golang: crypto/x509: crypto/x509: usage of IPv6 zone IDs can bypass URI name constraints'
    Description: A certificate with a URI which has a IPv6 address with a zone ID may incorrectly satisfy a URI name constraint that applies to the certificate chain. Certificates containing URIs are not permitted in the web PKI, so this only affects users of private PKIs which make use of URIs.
    Severity: MEDIUM
    VendorSeverity:
      bitnami: 2
      redhat: 1
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
        V3Score: 6.1
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.2
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45341
    - https://go.dev/cl/643099
    - https://go.dev/issue/71156
    - https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ
    - https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45341
    - https://pkg.go.dev/vuln/GO-2025-3373
    - https://www.cve.org/CVERecord?id=CVE-2024-45341
    PublishedDate: '2025-01-28T02:15:29.147Z'
    LastModifiedDate: '2025-01-28T16:15:38.65Z'
- Target: usr/bin/trivy
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-45336
    PkgID: stdlib@v1.22.10
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.22.10
      UID: 1bd59dbd5a538770
    InstalledVersion: v1.22.10
    FixedVersion: 1.22.11, 1.23.5, 1.24.0-rc.2
    Status: fixed
    Layer:
      Digest: sha256:27cf058be0e6ee775f4124c73b6d2a9c74f310531abd51cd3213434917fc0aca
      DiffID: sha256:422fe88498129205837a57b380c2d1dc362fe7793e3a99ed0d9fb43d20cd5840
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45336
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'golang: net/http: net/http: sensitive headers incorrectly sent after cross-domain redirect'
    Description: The HTTP client drops sensitive headers after following a cross-domain redirect. For example, a request to a.com/ containing an Authorization header which is redirected to b.com/ will not send that header to b.com. In the event that the client received a subsequent same-domain redirect, however, the sensitive headers would be restored. For example, a chain of redirects from a.com/, to b.com/1, and finally to b.com/2 would incorrectly send the Authorization header to b.com/2.
    Severity: MEDIUM
    VendorSeverity:
      bitnami: 2
      redhat: 2
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
        V3Score: 6.1
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N
        V3Score: 5.9
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45336
    - https://go.dev/cl/643100
    - https://go.dev/issue/70530
    - https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ
    - https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45336
    - https://pkg.go.dev/vuln/GO-2025-3420
    - https://www.cve.org/CVERecord?id=CVE-2024-45336
    PublishedDate: '2025-01-28T02:15:28.807Z'
    LastModifiedDate: '2025-01-28T16:15:38.22Z'
  - VulnerabilityID: CVE-2024-45341
    PkgID: stdlib@v1.22.10
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.22.10
      UID: 1bd59dbd5a538770
    InstalledVersion: v1.22.10
    FixedVersion: 1.22.11, 1.23.5, 1.24.0-rc.2
    Status: fixed
    Layer:
      Digest: sha256:27cf058be0e6ee775f4124c73b6d2a9c74f310531abd51cd3213434917fc0aca
      DiffID: sha256:422fe88498129205837a57b380c2d1dc362fe7793e3a99ed0d9fb43d20cd5840
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45341
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'golang: crypto/x509: crypto/x509: usage of IPv6 zone IDs can bypass URI name constraints'
    Description: A certificate with a URI which has a IPv6 address with a zone ID may incorrectly satisfy a URI name constraint that applies to the certificate chain. Certificates containing URIs are not permitted in the web PKI, so this only affects users of private PKIs which make use of URIs.
    Severity: MEDIUM
    VendorSeverity:
      bitnami: 2
      redhat: 1
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
        V3Score: 6.1
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.2
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45341
    - https://go.dev/cl/643099
    - https://go.dev/issue/71156
    - https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ
    - https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45341
    - https://pkg.go.dev/vuln/GO-2025-3373
    - https://www.cve.org/CVERecord?id=CVE-2024-45341
    PublishedDate: '2025-01-28T02:15:29.147Z'
    LastModifiedDate: '2025-01-28T16:15:38.65Z'
- Target: usr/bin/trivy_cve_query
  Class: lang-pkgs
  Type: gobinary
