- Target: nmaguiar/secutils:build (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-12798
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:616906adfb278aaf2ca9b4f179de5cd1fe81043128e6ac6a52ce16284552b56f
      DiffID: sha256:baf893a1d5320e1b3098918ccdb6b4f6e34fa57b426946a80dcb94c7832e9fb2
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12798
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: arbitrary code execution via JaninoEventEvaluator'
    Description: "ACE vulnerability in JaninoEventEvaluator  by QOS.CH logback-core\n      upto including version 0.1 to 1.3.14 and\_1.4.0 to 1.5.12 in Java applications allows\n      attacker to execute arbitrary code by compromising an existing\n      logback configuration file or by injecting an environment variable\n      before program execution.\n\n\n\n\n\nMalicious logback configuration files can allow the attacker to execute \narbitrary code using the JaninoEventEvaluator extension.\n\n\n\nA successful attack requires the user to have write access to a \nconfiguration file. Alternatively, the attacker could inject a malicious \nenvironment variable pointing to a malicious configuration file. In both \ncases, the attack requires existing privilege."
    Severity: MEDIUM
    CweIDs:
    - CWE-917
    VendorSeverity:
      ghsa: 2
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:H/A:L
        V3Score: 5.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12798
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/2cb6d520df7592ef1c3a198f1b5df3c10c93e183
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12798
    - https://www.cve.org/CVERecord?id=CVE-2024-12798
    PublishedDate: '2024-12-19T16:15:07.557Z'
    LastModifiedDate: '2025-01-03T14:15:24.37Z'
  - VulnerabilityID: CVE-2024-12801
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:616906adfb278aaf2ca9b4f179de5cd1fe81043128e6ac6a52ce16284552b56f
      DiffID: sha256:baf893a1d5320e1b3098918ccdb6b4f6e34fa57b426946a80dcb94c7832e9fb2
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12801
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: SaxEventRecorder vulnerable to Server-Side Request Forgery (SSRF) attacks'
    Description: "Server-Side Request Forgery (SSRF) in SaxEventRecorder by QOS.CH logback version 0.1 to 1.3.14 and 1.4.0 to 1.5.12\_ on the Java platform, allows an attacker to \nforge requests by compromising logback configuration files in XML.\n\n\n\nThe attacks involves the modification of DOCTYPE declaration in\_ XML configuration files."
    Severity: LOW
    CweIDs:
    - CWE-918
    VendorSeverity:
      ghsa: 1
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:N
        V3Score: 3.3
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12801
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/5f05041cba4c4ac0a62748c5c527a2da48999f2d
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12801
    - https://www.cve.org/CVERecord?id=CVE-2024-12801
    PublishedDate: '2024-12-19T17:15:08.93Z'
    LastModifiedDate: '2025-01-03T14:15:24.5Z'
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
- Target: usr/bin/grype
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-22871
    PkgID: stdlib@v1.24.1
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.24.1
      UID: 65ca895f24942279
    InstalledVersion: v1.24.1
    FixedVersion: 1.23.8, 1.24.2
    Status: fixed
    Layer:
      Digest: sha256:616906adfb278aaf2ca9b4f179de5cd1fe81043128e6ac6a52ce16284552b56f
      DiffID: sha256:baf893a1d5320e1b3098918ccdb6b4f6e34fa57b426946a80dcb94c7832e9fb2
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22871
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'net/http: Request smuggling due to acceptance of invalid chunked data in net/http'
    Description: The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.
    Severity: MEDIUM
    VendorSeverity:
      amazon: 3
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:N
        V3Score: 5.4
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/04/4
    - https://access.redhat.com/security/cve/CVE-2025-22871
    - https://go.dev/cl/652998
    - https://go.dev/issue/71988
    - https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk
    - https://nvd.nist.gov/vuln/detail/CVE-2025-22871
    - https://pkg.go.dev/vuln/GO-2025-3563
    - https://www.cve.org/CVERecord?id=CVE-2025-22871
    PublishedDate: '2025-04-08T20:15:20.183Z'
    LastModifiedDate: '2025-04-09T20:02:41.86Z'
- Target: usr/bin/syft
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-22871
    PkgID: stdlib@v1.24.1
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.24.1
      UID: c16316e32d1afd39
    InstalledVersion: v1.24.1
    FixedVersion: 1.23.8, 1.24.2
    Status: fixed
    Layer:
      Digest: sha256:616906adfb278aaf2ca9b4f179de5cd1fe81043128e6ac6a52ce16284552b56f
      DiffID: sha256:baf893a1d5320e1b3098918ccdb6b4f6e34fa57b426946a80dcb94c7832e9fb2
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22871
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'net/http: Request smuggling due to acceptance of invalid chunked data in net/http'
    Description: The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.
    Severity: MEDIUM
    VendorSeverity:
      amazon: 3
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:N
        V3Score: 5.4
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/04/4
    - https://access.redhat.com/security/cve/CVE-2025-22871
    - https://go.dev/cl/652998
    - https://go.dev/issue/71988
    - https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk
    - https://nvd.nist.gov/vuln/detail/CVE-2025-22871
    - https://pkg.go.dev/vuln/GO-2025-3563
    - https://www.cve.org/CVERecord?id=CVE-2025-22871
    PublishedDate: '2025-04-08T20:15:20.183Z'
    LastModifiedDate: '2025-04-09T20:02:41.86Z'
- Target: usr/bin/trivy
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-32386
    PkgID: helm.sh/helm/v3@v3.17.2
    PkgName: helm.sh/helm/v3
    PkgIdentifier:
      PURL: pkg:golang/helm.sh/helm/v3@v3.17.2
      UID: e21562ef302c4c3d
    InstalledVersion: v3.17.2
    FixedVersion: 3.17.3
    Status: fixed
    Layer:
      Digest: sha256:616906adfb278aaf2ca9b4f179de5cd1fe81043128e6ac6a52ce16284552b56f
      DiffID: sha256:baf893a1d5320e1b3098918ccdb6b4f6e34fa57b426946a80dcb94c7832e9fb2
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-32386
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'helm.sh/helm/v3: Helm Allows A Specially Crafted Chart Archive To Cause Out Of Memory Termination'
    Description: Helm is a tool for managing Charts. A chart archive file can be crafted in a manner where it expands to be significantly larger uncompressed than compressed (e.g., >800x difference). When Helm loads this specially crafted chart, memory can be exhausted causing the application to terminate. This issue has been resolved in Helm v3.17.3.
    Severity: MEDIUM
    CweIDs:
    - CWE-770
    - CWE-789
    VendorSeverity:
      bitnami: 2
      ghsa: 2
      redhat: 2
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
    References:
    - https://access.redhat.com/security/cve/CVE-2025-32386
    - https://github.com/helm/helm
    - https://github.com/helm/helm/commit/d8ca55fc669645c10c0681d49723f4bb8c0b1ce7
    - https://github.com/helm/helm/security/advisories/GHSA-4hfp-h4cw-hj8p
    - https://nvd.nist.gov/vuln/detail/CVE-2025-32386
    - https://www.cve.org/CVERecord?id=CVE-2025-32386
    PublishedDate: '2025-04-09T23:15:37.75Z'
    LastModifiedDate: '2025-04-11T15:40:10.277Z'
  - VulnerabilityID: CVE-2025-32387
    PkgID: helm.sh/helm/v3@v3.17.2
    PkgName: helm.sh/helm/v3
    PkgIdentifier:
      PURL: pkg:golang/helm.sh/helm/v3@v3.17.2
      UID: e21562ef302c4c3d
    InstalledVersion: v3.17.2
    FixedVersion: 3.17.3
    Status: fixed
    Layer:
      Digest: sha256:616906adfb278aaf2ca9b4f179de5cd1fe81043128e6ac6a52ce16284552b56f
      DiffID: sha256:baf893a1d5320e1b3098918ccdb6b4f6e34fa57b426946a80dcb94c7832e9fb2
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-32387
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'helm.sh/helm/v3: Helm Allows A Specially Crafted JSON Schema To Cause A Stack Overflow'
    Description: Helm is a package manager for Charts for Kubernetes. A JSON Schema file within a chart can be crafted with a deeply nested chain of references, leading to parser recursion that can exceed the stack size limit and trigger a stack overflow. This issue has been resolved in Helm v3.17.3.
    Severity: MEDIUM
    CweIDs:
    - CWE-121
    - CWE-674
    VendorSeverity:
      bitnami: 2
      ghsa: 2
      redhat: 2
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
    References:
    - https://access.redhat.com/security/cve/CVE-2025-32387
    - https://github.com/helm/helm
    - https://github.com/helm/helm/commit/d8ca55fc669645c10c0681d49723f4bb8c0b1ce7
    - https://github.com/helm/helm/security/advisories/GHSA-5xqw-8hwv-wg92
    - https://nvd.nist.gov/vuln/detail/CVE-2025-32387
    - https://www.cve.org/CVERecord?id=CVE-2025-32387
    PublishedDate: '2025-04-09T23:15:37.903Z'
    LastModifiedDate: '2025-04-11T15:40:10.277Z'
  - VulnerabilityID: CVE-2025-22871
    PkgID: stdlib@v1.24.1
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.24.1
      UID: 7aba090ce18913b7
    InstalledVersion: v1.24.1
    FixedVersion: 1.23.8, 1.24.2
    Status: fixed
    Layer:
      Digest: sha256:616906adfb278aaf2ca9b4f179de5cd1fe81043128e6ac6a52ce16284552b56f
      DiffID: sha256:baf893a1d5320e1b3098918ccdb6b4f6e34fa57b426946a80dcb94c7832e9fb2
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22871
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'net/http: Request smuggling due to acceptance of invalid chunked data in net/http'
    Description: The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.
    Severity: MEDIUM
    VendorSeverity:
      amazon: 3
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:N
        V3Score: 5.4
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/04/4
    - https://access.redhat.com/security/cve/CVE-2025-22871
    - https://go.dev/cl/652998
    - https://go.dev/issue/71988
    - https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk
    - https://nvd.nist.gov/vuln/detail/CVE-2025-22871
    - https://pkg.go.dev/vuln/GO-2025-3563
    - https://www.cve.org/CVERecord?id=CVE-2025-22871
    PublishedDate: '2025-04-08T20:15:20.183Z'
    LastModifiedDate: '2025-04-09T20:02:41.86Z'
- Target: usr/bin/trivy_cve_query
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-22871
    PkgID: stdlib@v1.24.1
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.24.1
      UID: b5fb81b8f7a10cb5
    InstalledVersion: v1.24.1
    FixedVersion: 1.23.8, 1.24.2
    Status: fixed
    Layer:
      Digest: sha256:616906adfb278aaf2ca9b4f179de5cd1fe81043128e6ac6a52ce16284552b56f
      DiffID: sha256:baf893a1d5320e1b3098918ccdb6b4f6e34fa57b426946a80dcb94c7832e9fb2
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22871
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'net/http: Request smuggling due to acceptance of invalid chunked data in net/http'
    Description: The net/http package improperly accepts a bare LF as a line terminator in chunked data chunk-size lines. This can permit request smuggling if a net/http server is used in conjunction with a server that incorrectly accepts a bare LF as part of a chunk-ext.
    Severity: MEDIUM
    VendorSeverity:
      amazon: 3
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:N
        V3Score: 5.4
    References:
    - http://www.openwall.com/lists/oss-security/2025/04/04/4
    - https://access.redhat.com/security/cve/CVE-2025-22871
    - https://go.dev/cl/652998
    - https://go.dev/issue/71988
    - https://groups.google.com/g/golang-announce/c/Y2uBTVKjBQk
    - https://nvd.nist.gov/vuln/detail/CVE-2025-22871
    - https://pkg.go.dev/vuln/GO-2025-3563
    - https://www.cve.org/CVERecord?id=CVE-2025-22871
    PublishedDate: '2025-04-08T20:15:20.183Z'
    LastModifiedDate: '2025-04-09T20:02:41.86Z'
