- Target: nmaguiar/secutils:build (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-12798
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:a4c2e6b10af5b9dbc00e1fff65507f808c164850bc8850e002a9399ca683501b
      DiffID: sha256:2c5d6e3e8975b3a9e146058d0cf58ab13f524229824f08d2732b9724c9a85e81
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12798
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: arbitrary code execution via JaninoEventEvaluator'
    Description: "ACE vulnerability in JaninoEventEvaluator  by QOS.CH logback-core\n      upto including version 0.1 to 1.3.14 and\_1.4.0 to 1.5.12 in Java applications allows\n      attacker to execute arbitrary code by compromising an existing\n      logback configuration file or by injecting an environment variable\n      before program execution.\n\n\n\n\n\nMalicious logback configuration files can allow the attacker to execute \narbitrary code using the JaninoEventEvaluator extension.\n\n\n\nA successful attack requires the user to have write access to a \nconfiguration file. Alternatively, the attacker could inject a malicious \nenvironment variable pointing to a malicious configuration file. In both \ncases, the attack requires existing privilege."
    Severity: MEDIUM
    CweIDs:
    - CWE-917
    VendorSeverity:
      ghsa: 2
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:H/A:L
        V3Score: 5.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12798
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/2cb6d520df7592ef1c3a198f1b5df3c10c93e183
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12798
    - https://www.cve.org/CVERecord?id=CVE-2024-12798
    PublishedDate: '2024-12-19T16:15:07.557Z'
    LastModifiedDate: '2025-01-03T14:15:24.37Z'
  - VulnerabilityID: CVE-2024-12801
    PkgName: ch.qos.logback:logback-core
    PkgPath: opt/dependency-check/lib/logback-core-1.2.13.jar
    PkgIdentifier:
      PURL: pkg:maven/ch.qos.logback/logback-core@1.2.13
      UID: 75945d17fdbc7707
    InstalledVersion: 1.2.13
    FixedVersion: 1.5.13, 1.3.15
    Status: fixed
    Layer:
      Digest: sha256:a4c2e6b10af5b9dbc00e1fff65507f808c164850bc8850e002a9399ca683501b
      DiffID: sha256:2c5d6e3e8975b3a9e146058d0cf58ab13f524229824f08d2732b9724c9a85e81
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12801
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback-core: SaxEventRecorder vulnerable to Server-Side Request Forgery (SSRF) attacks'
    Description: "Server-Side Request Forgery (SSRF) in SaxEventRecorder by QOS.CH logback version 0.1 to 1.3.14 and 1.4.0 to 1.5.12\_ on the Java platform, allows an attacker to \nforge requests by compromising logback configuration files in XML.\n\n\n\nThe attacks involves the modification of DOCTYPE declaration in\_ XML configuration files."
    Severity: LOW
    CweIDs:
    - CWE-918
    VendorSeverity:
      ghsa: 1
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:N
        V3Score: 3.3
    References:
    - https://access.redhat.com/security/cve/CVE-2024-12801
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/5f05041cba4c4ac0a62748c5c527a2da48999f2d
    - https://logback.qos.ch/news.html#1.3.15
    - https://logback.qos.ch/news.html#1.5.13
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12801
    - https://www.cve.org/CVERecord?id=CVE-2024-12801
    PublishedDate: '2024-12-19T17:15:08.93Z'
    LastModifiedDate: '2025-01-03T14:15:24.5Z'
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
- Target: usr/bin/grype
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-21613
    PkgID: github.com/go-git/go-git/v5@v5.12.0
    PkgName: github.com/go-git/go-git/v5
    PkgIdentifier:
      PURL: pkg:golang/github.com/go-git/go-git/v5@v5.12.0
      UID: 85cc486c0d3674bb
    InstalledVersion: v5.12.0
    FixedVersion: 5.13.0
    Status: fixed
    Layer:
      Digest: sha256:a4c2e6b10af5b9dbc00e1fff65507f808c164850bc8850e002a9399ca683501b
      DiffID: sha256:2c5d6e3e8975b3a9e146058d0cf58ab13f524229824f08d2732b9724c9a85e81
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-21613
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'go-git: argument injection via the URL field'
    Description: go-git is a highly extensible git implementation library written in pure Go. An argument injection vulnerability was discovered in go-git versions prior to v5.13. Successful exploitation of this vulnerability could allow an attacker to set arbitrary values to git-upload-pack flags. This only happens when the file transport protocol is being used, as that is the only protocol that shells out to git binaries. This vulnerability is fixed in 5.13.0.
    Severity: CRITICAL
    CweIDs:
    - CWE-88
    VendorSeverity:
      alma: 3
      azure: 3
      cbl-mariner: 3
      ghsa: 4
      oracle-oval: 3
      redhat: 3
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
        V3Score: 9.8
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H
        V3Score: 8.1
    References:
    - https://access.redhat.com/errata/RHSA-2025:0401
    - https://access.redhat.com/security/cve/CVE-2025-21613
    - https://bugzilla.redhat.com/2335888
    - https://bugzilla.redhat.com/2335901
    - https://errata.almalinux.org/8/ALSA-2025-0401.html
    - https://github.com/go-git/go-git
    - https://github.com/go-git/go-git/security/advisories/GHSA-v725-9546-7q7m
    - https://linux.oracle.com/cve/CVE-2025-21613.html
    - https://linux.oracle.com/errata/ELSA-2025-0401.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-21613
    - https://www.cve.org/CVERecord?id=CVE-2025-21613
    PublishedDate: '2025-01-06T17:15:47.043Z'
    LastModifiedDate: '2025-01-06T17:15:47.043Z'
  - VulnerabilityID: CVE-2025-21614
    PkgID: github.com/go-git/go-git/v5@v5.12.0
    PkgName: github.com/go-git/go-git/v5
    PkgIdentifier:
      PURL: pkg:golang/github.com/go-git/go-git/v5@v5.12.0
      UID: 85cc486c0d3674bb
    InstalledVersion: v5.12.0
    FixedVersion: 5.13.0
    Status: fixed
    Layer:
      Digest: sha256:a4c2e6b10af5b9dbc00e1fff65507f808c164850bc8850e002a9399ca683501b
      DiffID: sha256:2c5d6e3e8975b3a9e146058d0cf58ab13f524229824f08d2732b9724c9a85e81
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-21614
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'go-git: go-git clients vulnerable to DoS via maliciously crafted Git server replies'
    Description: go-git is a highly extensible git implementation library written in pure Go. A denial of service (DoS) vulnerability was discovered in go-git versions prior to v5.13. This vulnerability allows an attacker to perform denial of service attacks by providing specially crafted responses from a Git server which triggers resource exhaustion in go-git clients. Users running versions of go-git from v4 and above are recommended to upgrade to v5.13 in order to mitigate this vulnerability.
    Severity: HIGH
    CweIDs:
    - CWE-400
    - CWE-770
    VendorSeverity:
      alma: 3
      azure: 3
      cbl-mariner: 3
      ghsa: 3
      oracle-oval: 3
      redhat: 3
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/errata/RHSA-2025:0401
    - https://access.redhat.com/security/cve/CVE-2025-21614
    - https://bugzilla.redhat.com/2335888
    - https://bugzilla.redhat.com/2335901
    - https://errata.almalinux.org/8/ALSA-2025-0401.html
    - https://github.com/go-git/go-git
    - https://github.com/go-git/go-git/security/advisories/GHSA-r9px-m959-cxf4
    - https://linux.oracle.com/cve/CVE-2025-21614.html
    - https://linux.oracle.com/errata/ELSA-2025-0401.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-21614
    - https://www.cve.org/CVERecord?id=CVE-2025-21614
    PublishedDate: '2025-01-06T17:15:47.31Z'
    LastModifiedDate: '2025-01-06T17:15:47.31Z'
  - VulnerabilityID: CVE-2024-45338
    PkgID: golang.org/x/net@v0.32.0
    PkgName: golang.org/x/net
    PkgIdentifier:
      PURL: pkg:golang/golang.org/x/net@v0.32.0
      UID: 185c1ad429f359ad
    InstalledVersion: v0.32.0
    FixedVersion: 0.33.0
    Status: fixed
    Layer:
      Digest: sha256:a4c2e6b10af5b9dbc00e1fff65507f808c164850bc8850e002a9399ca683501b
      DiffID: sha256:2c5d6e3e8975b3a9e146058d0cf58ab13f524229824f08d2732b9724c9a85e81
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45338
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'golang.org/x/net/html: Non-linear parsing of case-insensitive content in golang.org/x/net/html'
    Description: An attacker can craft an input to the Parse functions that would be processed non-linearly with respect to its length, resulting in extremely slow parsing. This could cause a denial of service.
    Severity: HIGH
    CweIDs:
    - CWE-1333
    VendorSeverity:
      cbl-mariner: 3
      ghsa: 3
      redhat: 3
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45338
    - https://cs.opensource.google/go/x/net
    - https://github.com/golang/go/issues/70906
    - https://go-review.googlesource.com/c/net/+/637536
    - https://go.dev/cl/637536
    - https://go.dev/issue/70906
    - https://groups.google.com/g/golang-announce/c/wSCRmFnNmPA/m/Lvcd0mRMAwAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45338
    - https://pkg.go.dev/vuln/GO-2024-3333
    - https://ubuntu.com/security/notices/USN-7197-1
    - https://www.cve.org/CVERecord?id=CVE-2024-45338
    PublishedDate: '2024-12-18T21:15:08.173Z'
    LastModifiedDate: '2024-12-31T20:16:06.603Z'
- Target: usr/bin/syft
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-21613
    PkgID: github.com/go-git/go-git/v5@v5.12.0
    PkgName: github.com/go-git/go-git/v5
    PkgIdentifier:
      PURL: pkg:golang/github.com/go-git/go-git/v5@v5.12.0
      UID: baa08bd087dfadab
    InstalledVersion: v5.12.0
    FixedVersion: 5.13.0
    Status: fixed
    Layer:
      Digest: sha256:a4c2e6b10af5b9dbc00e1fff65507f808c164850bc8850e002a9399ca683501b
      DiffID: sha256:2c5d6e3e8975b3a9e146058d0cf58ab13f524229824f08d2732b9724c9a85e81
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-21613
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'go-git: argument injection via the URL field'
    Description: go-git is a highly extensible git implementation library written in pure Go. An argument injection vulnerability was discovered in go-git versions prior to v5.13. Successful exploitation of this vulnerability could allow an attacker to set arbitrary values to git-upload-pack flags. This only happens when the file transport protocol is being used, as that is the only protocol that shells out to git binaries. This vulnerability is fixed in 5.13.0.
    Severity: CRITICAL
    CweIDs:
    - CWE-88
    VendorSeverity:
      alma: 3
      azure: 3
      cbl-mariner: 3
      ghsa: 4
      oracle-oval: 3
      redhat: 3
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
        V3Score: 9.8
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H
        V3Score: 8.1
    References:
    - https://access.redhat.com/errata/RHSA-2025:0401
    - https://access.redhat.com/security/cve/CVE-2025-21613
    - https://bugzilla.redhat.com/2335888
    - https://bugzilla.redhat.com/2335901
    - https://errata.almalinux.org/8/ALSA-2025-0401.html
    - https://github.com/go-git/go-git
    - https://github.com/go-git/go-git/security/advisories/GHSA-v725-9546-7q7m
    - https://linux.oracle.com/cve/CVE-2025-21613.html
    - https://linux.oracle.com/errata/ELSA-2025-0401.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-21613
    - https://www.cve.org/CVERecord?id=CVE-2025-21613
    PublishedDate: '2025-01-06T17:15:47.043Z'
    LastModifiedDate: '2025-01-06T17:15:47.043Z'
  - VulnerabilityID: CVE-2025-21614
    PkgID: github.com/go-git/go-git/v5@v5.12.0
    PkgName: github.com/go-git/go-git/v5
    PkgIdentifier:
      PURL: pkg:golang/github.com/go-git/go-git/v5@v5.12.0
      UID: baa08bd087dfadab
    InstalledVersion: v5.12.0
    FixedVersion: 5.13.0
    Status: fixed
    Layer:
      Digest: sha256:a4c2e6b10af5b9dbc00e1fff65507f808c164850bc8850e002a9399ca683501b
      DiffID: sha256:2c5d6e3e8975b3a9e146058d0cf58ab13f524229824f08d2732b9724c9a85e81
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-21614
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'go-git: go-git clients vulnerable to DoS via maliciously crafted Git server replies'
    Description: go-git is a highly extensible git implementation library written in pure Go. A denial of service (DoS) vulnerability was discovered in go-git versions prior to v5.13. This vulnerability allows an attacker to perform denial of service attacks by providing specially crafted responses from a Git server which triggers resource exhaustion in go-git clients. Users running versions of go-git from v4 and above are recommended to upgrade to v5.13 in order to mitigate this vulnerability.
    Severity: HIGH
    CweIDs:
    - CWE-400
    - CWE-770
    VendorSeverity:
      alma: 3
      azure: 3
      cbl-mariner: 3
      ghsa: 3
      oracle-oval: 3
      redhat: 3
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/errata/RHSA-2025:0401
    - https://access.redhat.com/security/cve/CVE-2025-21614
    - https://bugzilla.redhat.com/2335888
    - https://bugzilla.redhat.com/2335901
    - https://errata.almalinux.org/8/ALSA-2025-0401.html
    - https://github.com/go-git/go-git
    - https://github.com/go-git/go-git/security/advisories/GHSA-r9px-m959-cxf4
    - https://linux.oracle.com/cve/CVE-2025-21614.html
    - https://linux.oracle.com/errata/ELSA-2025-0401.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-21614
    - https://www.cve.org/CVERecord?id=CVE-2025-21614
    PublishedDate: '2025-01-06T17:15:47.31Z'
    LastModifiedDate: '2025-01-06T17:15:47.31Z'
  - VulnerabilityID: CVE-2024-45338
    PkgID: golang.org/x/net@v0.32.0
    PkgName: golang.org/x/net
    PkgIdentifier:
      PURL: pkg:golang/golang.org/x/net@v0.32.0
      UID: c15b30163b6cc89
    InstalledVersion: v0.32.0
    FixedVersion: 0.33.0
    Status: fixed
    Layer:
      Digest: sha256:a4c2e6b10af5b9dbc00e1fff65507f808c164850bc8850e002a9399ca683501b
      DiffID: sha256:2c5d6e3e8975b3a9e146058d0cf58ab13f524229824f08d2732b9724c9a85e81
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45338
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'golang.org/x/net/html: Non-linear parsing of case-insensitive content in golang.org/x/net/html'
    Description: An attacker can craft an input to the Parse functions that would be processed non-linearly with respect to its length, resulting in extremely slow parsing. This could cause a denial of service.
    Severity: HIGH
    CweIDs:
    - CWE-1333
    VendorSeverity:
      cbl-mariner: 3
      ghsa: 3
      redhat: 3
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45338
    - https://cs.opensource.google/go/x/net
    - https://github.com/golang/go/issues/70906
    - https://go-review.googlesource.com/c/net/+/637536
    - https://go.dev/cl/637536
    - https://go.dev/issue/70906
    - https://groups.google.com/g/golang-announce/c/wSCRmFnNmPA/m/Lvcd0mRMAwAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45338
    - https://pkg.go.dev/vuln/GO-2024-3333
    - https://ubuntu.com/security/notices/USN-7197-1
    - https://www.cve.org/CVERecord?id=CVE-2024-45338
    PublishedDate: '2024-12-18T21:15:08.173Z'
    LastModifiedDate: '2024-12-31T20:16:06.603Z'
- Target: usr/bin/trivy
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/trivy_cve_query
  Class: lang-pkgs
  Type: gobinary
